server:
  port: 8888
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/muxin_dev?autoReconnect=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
          max-wait: 10000
          max-active: 50
          min-idle: 8
          test-on-borrow: true
          validation-query: select 1
mybatis:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatis-config.xml

logging:
  level:
    com.haylion.maascharge.dao.mapper.*: debug

